config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, skip: [:registrations]
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :posts
  resources :videos
  resources :photos
  resources :categories do
    resources :posts
  end
  root "pages#home"
  resources :pages, only: :home

end

app/models/activity.rb
class Activity < ActiveRecord::Base
end

app/models/article.rb
class Article < ActiveRecord::Base
  extend FriendlyId

  validates :title, presence: true, length: {minimum: 6, maximum: 200}

  friendly_id :title, use: :slugged
end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
  belongs_to :post
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  include RailsAdmin::CategoryAdmin
  extend FriendlyId
  friendly_id :name, use: :slugged

  validates :name, presence: true, length: {minimum: 6, maximum: 50}
  validates :description, presence: true, length: {minimum: 12}

  has_many :article_categories, dependent: :destroy
  has_many :posts, through: :article_categories

  friendly_id :name, use: :slugged

  has_attached_file :image,
                    :storage => :dropbox,
                    :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
                    :dropbox_visibility => 'private',
                    :path => "myblog/nice_images/:class/:attachment/:id_partition/:style/:filename",
                    :styles => {
                      :thumb => "140x140#",
                      :small  => "300x300#",
                      :medium => "500x500>" }
  #validates :image, attachment_presence: true
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  # add a delete_<asset_name> method:
  attr_accessor :delete_image
  before_validation { self.image.clear if self.delete_image == '2' }

  def in_country?
    self.name == Settings.except_cate.in_country
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :photo, inverse_of: :images
end

app/models/photo.rb
class Photo < Article
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true, reject_if: proc{|attributes| attributes[:url].blank?}

  has_attached_file :image, :styles => {
      :thumb => "140x140#",
      :small  => "200x200#",
      :medium => "300x300>" }
end

app/models/post.rb
class Post < Article
  include RailsAdmin::PostAdmin

  before_save :set_post_type_default

  has_many :article_categories, dependent: :destroy
  has_many :categories, through: :article_categories

  POST_ATTR = %i(category entry_id published_at title link image_url author
    short_content)
  OLD_TIME = 6.days.ago

  paginates_per Settings.limit.posts

  enum post_type: [:normal, :daily]

  has_attached_file(:image,
    :storage => :dropbox,
    :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
    :dropbox_visibility => 'private',
    :path => "myblog/nice_images/:class/:attachment/:id_partition/:style/:filename",
    :styles => {
      :thumb => "140x140#",
      :small  => "300x300#",
      :medium => "500x500>" })
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  attr_accessor :delete_image

  before_validation { self.image.clear if self.delete_image == '1' }

  scope :old_posts, ->{where("published_at < ?", OLD_TIME)}

  class << self
    def create_daily_posts! url
      posts = Rss::Google_news.new(url).fetch_data
      return [] unless posts.present?
      posts.each do |post|
        post_data = Rss::ExtractGoogleEntry.new post
        create_if_not_exist! post_data
      end
    end

    private
    def hash_t post_data
      attributes = Hash.new
      POST_ATTR.each do |attr|
        attributes[attr] = post_data.send attr
      end
      attributes.merge post_type: 1
    end

    def create_if_not_exist! post_data
      return if(Post.find_by_entry_id(post_data.entry_id) || !Category.exists?(name: post_data.category))
      Category.find_by_name(post_data.category).posts << Post.create(hash_t(post_data))
    end
  end

  private
  def set_post_type_default
    if published_at.nil? && post_type.nil?
      self.post_type = "normal"
      self.save
    end
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  scope :get_project_for_normal_user, ->{limit(2)}
  scope :for, ->user{user.admin? ? Project.all : Project.get_project_for_normal_user}
end

app/models/student.rb
class Student < ActiveRecord::Base
  validates :name, presence: true
  enum sex: {male: 0, female: 1}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :token_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  before_save :ensure_authentication_token

  validates :username, presence: true, length: {minimum: 6}
  validates :photo, presence: true
  validates :introduction, presence: true, length: {minimum: 16}

  enum role: [:normal, :admin]
end

app/models/video.rb
class Video < Article
  enum video_type: [:normal, :embed]

  validates :image, :video, presence: true

  has_attached_file :image, :styles => {
      :thumb => "140x140#",
      :small  => "200x200#",
      :medium => "300x300>" }
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    #binding.pry
  end

  def test
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :load_category, :load_post

  def show
  end

  private

  def load_category
    @category = Category.friendly.find params[:category_id]
  end

  def load_post
    @post = @category.posts.friendly.find params[:id]
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/posts/_post.html.erb
<%= div_for post do %>
  <%= content_tag :h3, link_to(post.title, category_post_path(@category, post), data: {no_turbolink: true}) if post.normal? %>
   <%= content_tag :h3, link_to(post.title, post.link, target: "_blank", data: {no_turbolink: true}) if post.daily? %>
  <p><span><i class="glyphicon glyphicon-time"></i> <%= (post.normal? ? post.created_at : post.published_at).in_time_zone(Settings.time_zone).strftime "%I:%M %p %d/%m/%Y" %></span> <span><i class="glyphicon glyphicon-pencil"></i> <%= link_to "Trần Huy Hoàng", "#" if post.normal? %><%= link_to post.author, "#" if post.daily? %></span></p>
  <div class="row">
    <div class="col-xs-16 col-md-4">
      <%= image_tag post.image.url(:thumb), class: "img-responsive" if post.normal? %>
      <%= image_tag "http://#{post.image_url}", class: "img-responsive", width: "130px" if post.daily? %>
    </div>
    <div class="col-xs-16 col-md-8">
      <%= sanitize truncate(post.content, :length => 200, escape: false, separator: " ") %>
      <p><%= sanitize post.short_content %><p>
      <p><strong><%= link_to " Đọc tiếp", category_post_path(@category, post), class: "read-more", data: {no_turbolink: true} if post.normal? %><%= link_to " Đọc tiếp", post.link, class: "read-more", target: "_blank", data: {no_turbolink: true} if post.daily? %></strong></p>
      <ul class="list-unstyled info-post">
        <li>260 lượt xem</li>
        <li title="Thích"><i class="glyphicon glyphicon-thumbs-up"></i> 13</li>
        <li title="Bình luận"><i class="glyphicon glyphicon-comment"></i> 27</li>
        <li title="Chia sẻ"><i class="glyphicon glyphicon-share-alt"></i> 15</li>
      </ul>
    </div>
  </div>
<% end %>

app/views/posts/show.html.erb
<% provide :title, @post.title %>
<div class="category-posts">
    <div class="top-bar">
        <h3 class="pull-left"><%= "#{@post.title}" %></h3>
        <div class="clearfix"></div>
    </div>

    <div class="content-post">
        <h3><%= @post.title %></h3>
        <div class="fb-like" style="margin-bottom: 6px;"></div>
        <%= sanitize @post.content %>
    </div>
    <div class="share-button">
      <%= social_share_button_tag @post.title, :popup => "true", :title=> @post.title %>
    </div>
</div>

<div class="comment-face">
  <div class="fb-comments" data-href="<%= category_post_url(@category, @post) %>" data-numposts="6"></div>
</div>