config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, skip: [:registrations]
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :posts
  resources :videos
  resources :photos
  resources :categories do
    resources :posts
  end
  root "pages#home"
  resources :pages, only: :home

end

app/models/activity.rb
class Activity < ActiveRecord::Base
end

app/models/article.rb
class Article < ActiveRecord::Base
  extend FriendlyId

  validates :title, presence: true, length: {minimum: 6, maximum: 200}

  friendly_id :title, use: :slugged
end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
  belongs_to :post
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  include RailsAdmin::CategoryAdmin
  extend FriendlyId
  friendly_id :name, use: :slugged

  validates :name, presence: true, length: {minimum: 6, maximum: 50}
  validates :description, presence: true, length: {minimum: 12}

  has_many :article_categories, dependent: :destroy
  has_many :posts, through: :article_categories

  friendly_id :name, use: :slugged

  has_attached_file :image,
                    :storage => :dropbox,
                    :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
                    :dropbox_visibility => 'private',
                    :path => "myblog/nice_images/:class/:attachment/:id_partition/:style/:filename",
                    :styles => {
                      :thumb => "140x140#",
                      :small  => "300x300#",
                      :medium => "500x500>" }
  #validates :image, attachment_presence: true
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  # add a delete_<asset_name> method:
  attr_accessor :delete_image
  before_validation { self.image.clear if self.delete_image == '2' }

  def in_country?
    self.name == Settings.except_cate.in_country
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :photo, inverse_of: :images
end

app/models/photo.rb
class Photo < Article
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true, reject_if: proc{|attributes| attributes[:url].blank?}

  has_attached_file :image, :styles => {
      :thumb => "140x140#",
      :small  => "200x200#",
      :medium => "300x300>" }
end

app/models/post.rb
class Post < Article
  include RailsAdmin::PostAdmin

  before_save :set_post_type_default

  has_many :article_categories, dependent: :destroy
  has_many :categories, through: :article_categories

  POST_ATTR = %i(category entry_id published_at title link image_url author
    short_content)
  OLD_TIME = 6.days.ago

  paginates_per Settings.limit.posts

  enum post_type: [:normal, :daily]

  has_attached_file(:image,
    :storage => :dropbox,
    :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
    :dropbox_visibility => 'private',
    :path => "myblog/nice_images/:class/:attachment/:id_partition/:style/:filename",
    :styles => {
      :thumb => "140x140#",
      :small  => "300x300#",
      :medium => "500x500>" })
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  attr_accessor :delete_image

  before_validation { self.image.clear if self.delete_image == '1' }

  scope :old_posts, ->{where("published_at < ?", OLD_TIME)}

  class << self
    def create_daily_posts! url
      posts = Rss::Google_news.new(url).fetch_data
      return [] unless posts.present?
      posts.each do |post|
        post_data = Rss::ExtractGoogleEntry.new post
        create_if_not_exist! post_data
      end
    end

    private
    def hash_t post_data
      attributes = Hash.new
      POST_ATTR.each do |attr|
        attributes[attr] = post_data.send attr
      end
      attributes.merge post_type: 1
    end

    def create_if_not_exist! post_data
      return if(Post.find_by_entry_id(post_data.entry_id) || !Category.exists?(name: post_data.category))
      Category.find_by_name(post_data.category).posts << Post.create(hash_t(post_data))
    end
  end

  private
  def set_post_type_default
    if published_at.nil? && post_type.nil?
      self.post_type = "normal"
      self.save
    end
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  scope :get_project_for_normal_user, ->{limit(2)}
  scope :for, ->user{user.admin? ? Project.all : Project.get_project_for_normal_user}
end

app/models/student.rb
class Student < ActiveRecord::Base
  validates :name, presence: true
  enum sex: {male: 0, female: 1}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :token_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  before_save :ensure_authentication_token

  validates :username, presence: true, length: {minimum: 6}
  validates :photo, presence: true
  validates :introduction, presence: true, length: {minimum: 16}

  enum role: [:normal, :admin]
end

app/models/video.rb
class Video < Article
  enum video_type: [:normal, :embed]

  validates :image, :video, presence: true

  has_attached_file :image, :styles => {
      :thumb => "140x140#",
      :small  => "200x200#",
      :medium => "300x300>" }
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    #binding.pry
  end

  def test
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/comments/new.html.haml
%h1 New comment
= simple_form_for @comment do |f|
  = f.input :content, as: :text
  = f.input :url, as: :file
  = f.button :submit

app/views/layouts/_footer.html.erb
<div class="footer container">
  <div class="row">
    <div class="col-xs-10">
      <ul class="nav nav-pills">
        <li><a href="#">Developers</a></li>
        <li><a href="#">Góp ý</a></li>
        <li><a href="#">Hướng dẫn</a></li>
      </ul>
      <p>&COPY; copyright by Tran Huy Hoang</p>
      <p>Đơn vị chủ quản: Heroku</p>
      <p>Giấy phép: none</p>
    </div>
    <div class="col-xs-2 scroll-top">
      <i class="glyphicon glyphicon-upload text-primary"></i>
    </div>
  </div>
 </div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("logo.jpg", class: "img-responsive logo"), root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Trang chủ</a></li>
        <li><a href="#">Giới thiệu</a></li>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Home Admin", rails_admin.dashboard_path %></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>
        <li><a href="#"><%= image_tag "anhdong.gif", size: "48", class: "img-responsive funy" %></a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="top-menu" style="margin-top: 0px;">
  <div class="container">
    <ul class="nav nav-tabs">
      <li><a href="<%= root_path %>"><i class="glyphicon glyphicon-home text-primary"></i></a></li>
      <% all_categories.each do |category| %>
        <% if category.in_country? %>
          <%= content_tag :li, link_to(Settings.except_cate.instead, category_path(category)) %>
        <% else %>
          <%= content_tag :li, link_to(category.name, category_path(category)) %>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/_sidebar.html.erb
<div class="col-xs-12 col-sm-3" id="sidebar">
  <div class="box-sidbar" id="new-posts">
    <div class="top-box-sidebar">
      <h3>Bài viết mới</h3>
    </div>
    <div class="content-box-side-bar">
      <ul class="list-posts list-unstyled">
      <% if @new_posts.present? %>
        <% @new_posts.each do |post| %>
          <li class="post">
          <h3><%= link_to post.title, post.link, target: "_blank" if post.daily? %><%= link_to post.title, category_post_path(post.categories.first, post) if post.normal? %></h3>
          <p><i class="glyphicon glyphicon-time"></i> <%= post.daily? ? post.published_at.in_time_zone(Settings.time_zone).strftime("%I:%M %p %d/%m/%Y") : post.created_at.in_time_zone(Settings.time_zone).strftime("%I:%M %p %d/%m/%Y") %></p>
          <p><i class="glyphicon glyphicon-pencil"></i> <a href="#"><%= post.daily? ? post.author : Settings.author_default %></a></p>
        </li>
        <% end %>
      <% end %>
      </ul>
    </div>
  </div>

    <div class="box-sidbar" id="new-videos">
      <div class="top-box-sidebar">
        <h3>Video mới</h3>
      </div>
      <div class="content-box-side-bar">
        <div class="frame-video">
          <iframe width="100%" height="200px" src="https://www.youtube.com/embed/D3Xh6rDviv0" frameborder="0" allowfullscreen></iframe>
        </div>
      </div>
    </div>

    <div class="box-sidbar" id="new-album-photo">
      <div class="top-box-sidebar">
        <h3>Album ảnh mới</h3>
      </div>
      <div class="content-box-side-bar">
        <ul class="list-posts list-unstyled">
          <li class="post">
            <div class="image-post">
              <%= image_tag "img8.jpg" , class: "img-responsive img-thumbnail" %>
            </div>
            <h3><a href="#">Ngẫu hứng ngày thu</a></h3>
            <p><i class="glyphicon glyphicon-time"></i> 10:20 20/9/2015</p>
          </li>
          <li class="post">
            <div class="image-post">
              <%= image_tag "img8.jpg" , class: "img-responsive img-thumbnail" %>
            </div>
            <h3><a href="#">Lặng lẽ</a></h3>
            <p><i class="glyphicon glyphicon-time"></i> 10:20 20/9/2015</p>
          </li>
          <li class="post">
            <div class="image-post">
              <%= image_tag "img8.jpg" , class: "img-responsive img-thumbnail" %>
            </div>
            <h3><a href="#">Gọi mưa về trong đêm</a></h3>
            <p><i class="glyphicon glyphicon-time"></i> 10:20 20/9/2015</p>
          </li>
        </ul>
      </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="http://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
  <title><%= yield(:title) %> | Tran Huy Hoang</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v2.5&appId=1004885359555624";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>



<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v2.5&appId=1570513946503020";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

  <%= render "layouts/header" %>
  <div class="content container">
    <div class="row">
        <div class="col-xs-12 col-sm-9" id="primary">
          <% if flash %>
            <% flash.each do |key, msg| %>
              <div class="alert alert-<%= key == :notice ? "info" : "danger" %> alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <%= msg %>
              </div>
            <% end %>
          <% end %>
          <%= yield %>
        </div>
        <%= render "layouts/sidebar" %>
    </div>
  </div>
  <%= render "layouts/footer" %>
</body>
</html>

app/views/pages/test.html.erb
<div class="btn-group" style="margin-bottom: 15px;">
  <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Select language <span class="caret"></span>
  </button>
  <ul class="dropdown-menu">
    <li><%= link_to "Vietnamese", url_for(lang: "vie"), data: {no_turbolink: true} %></li>
    <li><%= link_to "English", url_for(lang: "en"), data: {no_turbolink: true} %></li>
  </ul>
</div>
<div class="translate">
  <button class="btn btn-info" id="btn-show-one">Click me!</button>
</div>

<button type="button" class="btn btn-primary btn-lg modal-show" data-toggle="modal" data-target="#myModal" style="display: none">
  Launch demo modal
</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"></h4>
      </div>
      <div class="modal-body show-result">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>